### ISSUE TITLE
changes added to ficdown.js

### ISSUE THREAD

**Issue by ByFernanz** [rudism/ficdown.js#10]
cordial greeting. For the Hispanic community I have prepared a repository to easily use the Ficdown player in Javascript, some slight modifications were also made, such as allowing the insertion of javascript code in the scenes and the possibility of choosing between a vertical reading such as Ink or One reading scene by scene Twine style.

[https://github.com/ByFernanz/ficdownjs-webplayer](https://github.com/ByFernanz/ficdownjs-webplayer)

**Comment by rudism** [comment]
You should take a look at the latest version. Rewritten in typescript and also supports the things you mentioned you have added to your fork.
