### ISSUE TITLE
Add some configurable options

### ISSUE THREAD

**Issue by rudism** [rudism/Ficdown.js#3]
Needs ability to define certain behaviors of the game engine, for example:
- Paged mode versus continuous scroll
- Customize begin and start over text

**Comment by rudism** [comment]
Partially addressed, you can now pass two additional parameters to the `Player` constructor to override the text used for the start link, and markdown to be rendered for the "game over" state.

```javascript
new Player(story, 'main', 'Click here to start...', '## Game Over\n\n[Click here](/main) to restart.')
```

**Comment by starvingindie** [comment]
Paged mode would be super awesome. Also thanks for implementing the Begin and Start Over Text.
