### ISSUE TITLE
Feature Request: Single HTML File

### ISSUE THREAD

**Issue by starvingindie** [rudism/Ficdown.js#7]
It would be awesome to have a tool that reads in a markdown file and then exports out a single HTML Ficdown file.

Currently, because the HTML file reads in an external MD file, it requires you to host the game on a server in order to play. If all the dependencies of Ficdown were baked into a single HTML file, including the MD text - authors can distribute their games without having players needing to know how to host/serve the game. Essentially, It would allow players to play games offline, kind of like Twine a game.

**Comment by rudism** [comment]
This can be achieved by throwing the markdown content into an element on the page, then retrieving that into a variable and passing it to the player.

See the [test.html](https://github.com/rudism/Ficdown.js/blob/master/test.html) example, which works just fine offline.
